# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9eb3d12f28c2f1d80ee2042aaeb1df7943dd022219cc9b4c938fbcfdbbf6417d66185c468a2aa6eca1bd702390e841b276a0f104954ca45eb4ba65cd0fda6f7

test:
  secret_key_base: 2dd7165ec8edd2bf3423e91d557f23c69a9e1bc328c84dc28f99ae31d0326ac96d477ee993d86c6734b2ba679a312c683d41d8f11a5734e81d79f01297912ba1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
